name: Zola publish

on:
  push:
    branches:
      - master 
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref != 'refs/heads/master'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: 'Build only' 
        uses: shalzz/zola-deploy-action@master
        env:
          BUILD_DIR: .
          TOKEN: ${{ secrets.ZOLA_TOKEN }}
          BUILD_ONLY: true
  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@master
      - name: Clone Jigsaw build files
        run: |
            # Clone build branch into separate directory
            mkdir /tmp/jigsaw/
            git clone --branch build --single-branch https://github.com/kneasle/3rd-yr-proj.git /tmp/jigsaw
            # Copy the required folders into this one
            mkdir static/jigsaw
            cd static/jigsaw
            mv /tmp/jigsaw/firehose .
      - name: 'Build and deploy'
        uses: shalzz/zola-deploy-action@master
        env:
          PAGES_BRANCH: gh-pages
          BUILD_DIR: .
          TOKEN: ${{ secrets.ZOLA_TOKEN }}
